import * as fs from 'fs';
import * as path from 'path';
import { ok, fail } from '../lib/response';
import { ToolDefinition, ToolResponse, ToolExecutor } from '../types';
import { z } from '../lib/schema';
import { mcpTool, defineToolsFromDecorators } from '../lib/decorators';

export class ServerTools implements ToolExecutor {
    private readonly exec: ToolExecutor;

    constructor() {
        this.exec = defineToolsFromDecorators(this);
    }

    getTools(): ToolDefinition[] { return this.exec.getTools(); }
    execute(toolName: string, args: any): Promise<ToolResponse> { return this.exec.execute(toolName, args); }


    @mcpTool({
        name: 'get_build_hash',
        title: 'Read extension build hash',
        description: '[specialist] Read the build identity (MD5 of dist/main.js + git SHA + buildTime) from dist/build-hash.json. Generated by postbuild script after each npm run build.',
        inputSchema: z.object({}),
    })
    async getBuildHash(): Promise<ToolResponse> {
        const hashFile = path.join(__dirname, '../build-hash.json');
        let info: any;
        try {
            info = JSON.parse(fs.readFileSync(hashFile, 'utf8'));
        } catch (e: any) {
            if (e?.code === 'ENOENT') {
                return ok({ buildHash: 'dev', gitSha: 'unknown', buildTime: null, note: 'build-hash.json not found — run npm run build to generate it' });
            }
            return fail(`Failed to read build-hash.json: ${e.message}`);
        }
        return ok({ buildHash: info.buildHash ?? 'dev', gitSha: info.gitSha ?? 'unknown', buildTime: info.buildTime ?? null });
    }

    @mcpTool({
        name: 'check_code_sync',
        title: 'Check extension code sync',
        description: '[specialist] Compare source TypeScript mtime against dist/build-hash.json buildTime. Returns inSync: true when all .ts files are older than the last build, with a list of stale files otherwise.',
        inputSchema: z.object({
            sourceRoot: z.string().optional().describe('Absolute path to the source directory to scan. Defaults to the extension source/ directory.'),
        }),
    })
    async checkCodeSync(args: { sourceRoot?: string }): Promise<ToolResponse> {
        const extRoot = path.join(__dirname, '../..');
        const hashFile = path.join(__dirname, '../build-hash.json');
        let buildInfo: any = null;
        try { buildInfo = JSON.parse(fs.readFileSync(hashFile, 'utf8')); } catch {}
        if (!buildInfo?.buildTime) {
            return ok({ inSync: false, buildInfo: null, staleSourceFiles: [], message: 'No build-hash.json found — run npm run build first' });
        }
        const buildTime = new Date(buildInfo.buildTime).getTime();
        const srcRoot = path.resolve(args.sourceRoot ?? path.join(extRoot, 'source'));
        const resolvedExt = path.resolve(extRoot);
        const rel = path.relative(resolvedExt, srcRoot);
        if (rel.startsWith('..') || path.isAbsolute(rel)) {
            return fail('sourceRoot must be within the extension root');
        }
        const staleSourceFiles: string[] = [];
        const walk = (dir: string): void => {
            if (!fs.existsSync(dir)) return;
            for (const entry of fs.readdirSync(dir, { withFileTypes: true })) {
                const full = path.join(dir, entry.name);
                if (entry.isDirectory()) { walk(full); continue; }
                if (!entry.name.endsWith('.ts')) continue;
                if (fs.statSync(full).mtimeMs > buildTime) {
                    staleSourceFiles.push(full.replace(extRoot + path.sep, '').replace(/\\/g, '/'));
                }
            }
        };
        walk(srcRoot);
        staleSourceFiles.sort();
        const inSync = staleSourceFiles.length === 0;
        return ok({
            inSync,
            buildInfo,
            staleSourceFiles,
            message: inSync
                ? 'Extension is in sync with the latest build'
                : `${staleSourceFiles.length} source file(s) newer than last build — run npm run build`,
        });
    }

    @mcpTool({
        name: 'query_server_ip_list',
        title: 'Read server IP list',
        description: '[specialist] Read IPs reported by the Cocos Editor server. No project side effects; use to build client connection URLs.',
        inputSchema: z.object({}),
    })
    async queryServerIPList(): Promise<ToolResponse> {
        const ipList: string[] = await Editor.Message.request('server', 'query-ip-list');
        return ok({
                ipList: ipList,
                count: ipList.length,
                message: 'IP list retrieved successfully'
            });
    }

    @mcpTool({
        name: 'query_sorted_server_ip_list',
        title: 'Read sorted server IPs',
        description: '[specialist] Read the Editor server IP list in preferred order. No project side effects.',
        inputSchema: z.object({}),
    })
    async querySortedServerIPList(): Promise<ToolResponse> {
        const sortedIPList: string[] = await Editor.Message.request('server', 'query-sort-ip-list');
        return ok({
                sortedIPList: sortedIPList,
                count: sortedIPList.length,
                message: 'Sorted IP list retrieved successfully'
            });
    }

    @mcpTool({
        name: 'query_server_port',
        title: 'Read server port',
        description: '[specialist] Read the current Cocos Editor server port. Does not start or stop any server.',
        inputSchema: z.object({}),
    })
    async queryServerPort(): Promise<ToolResponse> {
        const port: number = await Editor.Message.request('server', 'query-port');
        return ok({
                port: port,
                message: `Editor server is running on port ${port}`
            });
    }

    @mcpTool({
        name: 'get_server_status',
        title: 'Read server status',
        description: '[specialist] Collect Editor server IP/port, MCP port, Cocos version, platform, and Node runtime info. Diagnostics only.',
        inputSchema: z.object({}),
    })
    async getServerStatus(): Promise<ToolResponse> {
        try {
            // Gather comprehensive server information
            const [ipListResult, portResult] = await Promise.allSettled([
                this.queryServerIPList(),
                this.queryServerPort()
            ]);

            const status: any = {
                timestamp: new Date().toISOString(),
                serverRunning: true
            };

            if (ipListResult.status === 'fulfilled' && ipListResult.value.success) {
                status.availableIPs = ipListResult.value.data.ipList;
                status.ipCount = ipListResult.value.data.count;
            } else {
                status.availableIPs = [];
                status.ipCount = 0;
                status.ipError = ipListResult.status === 'rejected' ? ipListResult.reason : ipListResult.value.error;
            }

            if (portResult.status === 'fulfilled' && portResult.value.success) {
                status.port = portResult.value.data.port;
            } else {
                status.port = null;
                status.portError = portResult.status === 'rejected' ? portResult.reason : portResult.value.error;
            }

            // Add additional server info
            status.mcpServerPort = 3000; // Our MCP server port
            status.editorVersion = (Editor as any).versions?.cocos || 'Unknown';
            status.platform = process.platform;
            status.nodeVersion = process.version;

            return ok(status);

        } catch (err: any) {
            return fail(`Failed to get server status: ${err.message}`);
        }
    }

    @mcpTool({
        name: 'check_server_connectivity',
        title: 'Check server connectivity',
        description: '[specialist] Probe Editor.Message connectivity with server/query-port and a timeout. No project side effects.',
        inputSchema: z.object({
            timeout: z.number().default(5000).describe('Editor server response timeout in milliseconds. Default 5000.'),
        }),
    })
    async checkServerConnectivity(args: { timeout?: number }): Promise<ToolResponse> {
        const timeout = args.timeout ?? 5000;
        const startTime = Date.now();
            
        try {
            // Test basic Editor API connectivity
            const testPromise = Editor.Message.request('server', 'query-port');
            const timeoutPromise = new Promise((_, reject) => {
                setTimeout(() => reject(new Error('Connection timeout')), timeout);
            });

            await Promise.race([testPromise, timeoutPromise]);
                
            const responseTime = Date.now() - startTime;
                
            return ok({
                    connected: true,
                    responseTime: responseTime,
                    timeout: timeout,
                    message: `Server connectivity confirmed in ${responseTime}ms`
                });

        } catch (err: any) {
            const responseTime = Date.now() - startTime;
                
            return {
                success: false,
                data: {
                    connected: false,
                    responseTime: responseTime,
                    timeout: timeout,
                    error: err.message
                }
            };
        }
    }

    @mcpTool({
        name: 'get_network_interfaces',
        title: 'Read network interfaces',
        description: '[specialist] Read OS network interfaces and compare with Editor-reported IPs. Diagnostics only.',
        inputSchema: z.object({}),
    })
    async getNetworkInterfaces(): Promise<ToolResponse> {
        try {
            // Get network interfaces using Node.js os module
            const os = require('os');
            const interfaces = os.networkInterfaces();
                
            const networkInfo = Object.entries(interfaces).map(([name, addresses]: [string, any]) => ({
                name: name,
                addresses: addresses.map((addr: any) => ({
                    address: addr.address,
                    family: addr.family,
                    internal: addr.internal,
                    cidr: addr.cidr
                }))
            }));

            // Also try to get server IPs for comparison
            const serverIPResult = await this.queryServerIPList();
                
            return ok({
                    networkInterfaces: networkInfo,
                    serverAvailableIPs: serverIPResult.success ? serverIPResult.data.ipList : [],
                    message: 'Network interfaces retrieved successfully'
                });

        } catch (err: any) {
            return fail(`Failed to get network interfaces: ${err.message}`);
        }
    }
}
